In [1]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [2]:
train_images.shape

(60000, 28, 28)

In [3]:
len(train_labels)


60000

In [4]:
train_labels


array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [5]:
test_images.shape


(10000, 28, 28)

In [6]:
len(test_labels)


10000

In [7]:
test_labels


array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [8]:
from tensorflow.keras import models
from tensorflow.keras import layers
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

In [9]:
network.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

In [10]:
train_images = train_images.reshape((60000, 28 * 28))
train_images

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [11]:
train_images = train_images.astype('float32') / 255
train_images

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [12]:
test_images = test_images.reshape((10000, 28 * 28))
test_images

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [13]:
test_images = test_images.astype('float32') / 255
test_images

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [14]:
from tensorflow.keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [15]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 10s 171us/sample - loss: 0.2562 - accuracy: 0.9269
Epoch 2/5
60000/60000 [==============================] - 4s 73us/sample - loss: 0.1041 - accuracy: 0.9688
Epoch 3/5
60000/60000 [==============================] - 4s 73us/sample - loss: 0.0685 - accuracy: 0.9794
Epoch 4/5
60000/60000 [==============================] - 4s 74us/sample - loss: 0.0496 - accuracy: 0.9851
Epoch 5/5
60000/60000 [==============================] - 5s 79us/sample - loss: 0.0376 - accuracy: 0.9887
